name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ncc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: npm run dist
        run: |-
          npm ci
          npm run dist
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated Build"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "npm run dist" || exit 0
          git push
